services:
  api:
    container_name: codered-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    restart: always
    env_file:
      - ./.env/api-config
      - ./.env/database-pass
    volumes:
      - ./src:/opt/codered/api/src
    ports:
      - 3000:3000
    networks:
      - base
    stdin_open: true
    tty: true

  db:
    container_name: codered-db
    image: mariadb:11.4
    restart: always
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 2s
      start_interval: 2s
      interval: 5s
      timeout: 5s
      retries: 10
    env_file:
      - ./.env/database-pass
    volumes:
      - ./.data:/var/lib/mysql
    networks:
      - base

networks:
  base:
    driver: bridge
